services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    contao_remember_language.listener.frontend:
        class: InspiredMinds\ContaoRememberLanguage\EventListener\FrontendListener
        arguments: ['@service_container']
        public: true
